### ISSUE TITLE
LUA errors 1.4.5 SoD login error

### ISSUE THREAD

**Issue by GregoryGH** [Road-block/WaylaidTooltipHelper#1]
15x WaylaidTooltipHelper/core.lua:149: attempt to compare number with nil
[string "@WaylaidTooltipHelper/core.lua"]:149: in function `Alert'
[string "@WaylaidTooltipHelper/core.lua"]:442: in function `?'
[string "@WaylaidTooltipHelper/core.lua"]:15: in function <WaylaidTooltipHelper/core.lua:14>

Locals:
self = <table> {
 needCache = <table> {
 }
 supplyCache = <table> {
 }
 PLAYER_ENTERING_WORLD = <function> defined @WaylaidTooltipHelper/core.lua:436
 _factionName = "Azeroth Commerce Authority"
 FilledDetails = <function> defined @WaylaidTooltipHelper/core.lua:305
 HaveFilledSupply = <function> defined @WaylaidTooltipHelper/core.lua:223
 _standing = 4
 _playerMaxLevel = 25
_playerLevel = 5
 AddWaypoint = <function> defined @TomTom/TomTom.lua:966
 _supplyFaction = 2586
 Alert = <function> defined @WaylaidTooltipHelper/core.lua:147
 ADDON_LOADED = <function> defined @WaylaidTooltipHelper/core.lua:402
 _repMultiplier = 1.100000
 PLAYER_CONTROL_LOST = <function> defined @WaylaidTooltipHelper/core.lua:467
 PLAYER_LEVEL_UP = <function> defined @WaylaidTooltipHelper/core.lua:455
 Print = <function> defined @WaylaidTooltipHelper/core.lua:142
 CacheItems = <function> defined @WaylaidTooltipHelper/core.lua:196
 db = <table> {
 }
 L = <table> {
 }
 RemoveWaypoint = <function> defined @TomTom/TomTom.lua:869
UPDATE_FACTION = <function> defined @WaylaidTooltipHelper/core.lua:448
 HaveEmptySupply = <function> defined @WaylaidTooltipHelper/core.lua:241
 AddTipInfo = <function> defined @WaylaidTooltipHelper/core.lua:316
 ZONE_CHANGED_NEW_AREA = <function> defined @WaylaidTooltipHelper/core.lua:460
 short = "|cff00c6d1WttH|r"
 filledCache = <table> {
 }
 SupplyDetails = <function> defined @WaylaidTooltipHelper/core.lua:295
 label = "|cff00c6d1WaylaidTooltipHelper|r"
 PLAYER_LOGIN = <function> defined @WaylaidTooltipHelper/core.lua:420
 PLAYER_UNGHOST = <function> defined @WaylaidTooltipHelper/core.lua:460
 CalculateRewards = <function> defined @WaylaidTooltipHelper/core.lua:259
 PLAYER_CONTROL_GAINED = <function> defined @WaylaidTooltipHelper/core.lua:474
 PLAYER_ALIVE = <function> defined @WaylaidTooltipHelper/core.lua:460
 SetupFaction = <function> defined @WaylaidTooltipHelper/core.lua:383
}
mapID = 1415
(*temporary) = nil
(*temporary) = 1
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = "attempt to compare number with nil"
standingToPhase = <table> {
 5 = 1
 6 = 2
 7 = 3
 8 = 4
}
SoD_Phase = 1
factionNPCS = <table> {
 2586 = <table> {
 }
 2587 = <table> {
 }
}
addon = <table> {
 needCache = <table> {
 }
 supplyCache = <table> {
 }
 PLAYER_ENTERING_WORLD = <function> defined @WaylaidTooltipHelper/core.lua:436
 _factionName = "Azeroth Commerce Authority"
 FilledDetails = <function> defined @WaylaidTooltipHelper/core.lua:305
 HaveFilledSupply = <function> defined @WaylaidTooltipHelper/core.lua:223
 _standing = 4
_playerMaxLevel = 25
 _playerLevel = 5
 AddWaypoint = <function> defined @TomTom/TomTom.lua:966
 _supplyFaction = 2586
 Alert = <function> defined @WaylaidTooltipHelper/core.lua:147
 ADDON_LOADED = <function> defined @WaylaidTooltipHelper/core.lua:402
 _repMultiplier = 1.100000
 PLAYER_CONTROL_LOST = <function> defined @WaylaidTooltipHelper/core.lua:467
 PLAYER_LEVEL_UP = <function> defined @WaylaidTooltipHelper/core.lua:455
 Print = <function> defined @WaylaidTooltipHelper/core.lua:142
 CacheItems = <function> defined @WaylaidTooltipHelper/core.lua:196
 db = <table> {
 }
 L = <table> {
 }
RemoveWaypoint = <function> defined @TomTom/TomTom.lua:869
 UPDATE_FACTION = <function> defined @WaylaidTooltipHelper/core.

**Comment by Road-block** [comment]
Thanks for the report. Should be fixed in https://github.com/Road-block/WaylaidTooltipHelper/commit/a79ada639ded3292be70798acef6cd59f0d78d0c
