### ISSUE TITLE
LUA errors 1.4.5 SoD item tooltip error

### ISSUE THREAD

**Issue by GregoryGH** [Road-block/WaylaidTooltipHelper#2]
99x WaylaidTooltipHelper/core.lua:326: attempt to compare number with nil
[string "@WaylaidTooltipHelper/core.lua"]:326: in function <WaylaidTooltipHelper/core.lua:316>
[string "=[C]"]: ?
[string "=[C]"]: ?
[string "=[C]"]: ?
[string "=[C]"]: ?
[string "=[C]"]: ?
[string "=[C]"]: ?
[string "=[C]"]: ?
[string "=[C]"]: in function `SetHyperlink'
[string "@aux-addon/util/info.lua"]:137: in function `set_tooltip'
[string "@aux-addon/gui/item_listing.lua"]:99: in function <aux-addon/gui/item_listing.lua:98>

Locals:
self = GameTooltip {
 0 = <userdata>
 OnBackdropLoaded = <function> defined @SharedXML/Backdrop.lua:152
 GetBackdropColor = <function> defined @SharedXML/Backdrop.lua:390
 SetHyperlink = <function> defined =[C]:-1
 SetTradeSkillItem = <function> defined =[C]:-1
 RightEdge = Texture {
 }
 SetEngravingRune = <function> defined =[C]:-1
 ClearBackdrop = <function> defined =[C]:-1
 SetPetAction = <function> defined =[C]:-1
 SetLootItem = <function> defined =[C]:-1
 FadeOut = <function> defined =[C]:-1
 SetBuybackItem = <function> defined =[C]:-1
 SetMerchantItem = <function> defined =[C]:-1
 SetupTextureCoordinates = <function> defined @SharedXML/Backdrop.lua:214
 HasBackdropInfo = <function> defined @SharedXML/Backdrop.lua:278
 ttIcon = Texture {
 }
 GetEdgeSize = <function> defined @SharedXML/Backdrop.lua:188
 updateTooltip = 0.115000
 SetInventoryItem = <function> defined =[C]:-1
 TopEdge = Texture {
 }
 ttCount = FontString {
 }
 TooltipBackdropOnLoad = <function> defined @SharedXML/SharedTooltipTemplates.lua:275
 SetAuctionSellItem = <function> defined =[C]:-1
 SetBagItem = <function> defined =[C]:-1
 SetAction = <function> defined =[C]:-1
 SetBackdropColor = <function> defined =[C]:-1
 LeftEdge = Texture {
 }
 SetAuctionItem = <function> defined =[C]:-1
 ttSetIconTextureAndText = <function> defined @TipTacItemRef/ttItemRef.lua:320
 SetSpellBookItem = <function> defined =[C]:-1
 SetCurrencyToken = <function> defined =[C]:-1
 SetBackdropBorderColor = <function> defined =[C]:-1
 SetOwner = <function> defined =[C]:-1
 SetCraftItem = <function> defined =[C]:-1
 ApplyBackdrop = <function> defined =[C]:-1
 SetBackdrop = <function> defined =[C]:-1
 TopOverlay = Texture {
 }
 GetBackdropBorderColor = <function> defined @SharedXML/Backdrop.lua:409
 GetBackdrop = <function> defined @SharedXML/Backdrop.lua:347
 SetUnitDebuff = <function> defined =[C]:-1
 SetItemByID = <function> defined =[C]:-1
 SetQuestItem = <function> defined =[C]:-1
 comparing = false
 SetBorderBlendMode = <function> defined @SharedXML/Backdrop.lua:266
 SetToyByItemID = <function> defined =[C]:-1
 __tooltipUpdated = true
 SetUnit = <function> defined =[C]:-1
 SetInboxItem = <function> defined =[C]:-1
 shoppingTooltips = <table> {
 }
 Center = Texture {
 }
 SetLFGDungeonShortageReward = <function> defined =[C]:-1
 SetQuestLogItem = <function> defined =[C]:-1
 OnBackdropSizeChanged = <function> defined @SharedXML/Backdrop.lua:182
 SetUnitBuff = <function> defined =[C]:-1
 BottomLeftCorner = Texture {
 }
 SetTradePlayerItem = <function> defined =[C]:-1
 BottomEdge = Texture {
 }
 SetSendMailItem = <function> defined =[C]:-1
 SetTradeTargetItem = <function> defined =[C]:-1
 BottomRightCorner = Texture {
 }
 TopRightCorner = Texture {
 }
 TopLeftCorner = Texture {
 }
 backdropInfo = <table> {
 }
 NineSlice = Frame {
 }
 SetUnitAura = <function> defined =[C]:-1
 SetLFGDungeonReward = <function> defined =[C]:-1
 SetCurrencyTokenByID = <function> defined =[C]:-1
 SetCraftSpell = <function> defined =[C]:-1
 needsReset = false
 SetupPieceVisuals = <function> defined @SharedXML/Backdrop.lua:246
 SetQuestCurrency = <function> defined =[C]:-1
 SetQuestLogCurrency = <function> defined =[C]:-1
 BottomOverlay = Texture {
 }
}
tooltip = GameTooltip {
 0 = <userdata>
 OnBackdropLoaded = <function> defined @SharedXML/Backdrop.lua:152
 GetBackdropColor = <function> defined @SharedXML/Backdrop.lua:390
 SetHyperlink = <function> defined =[C]:-1
 SetTradeSkillItem = <function> defined =[C]:-1
 RightEdge = Texture {
 }
 SetEngravingRune = <function> defined =[C]:-1
 ClearBackdrop = <function> defined =[C]:-1
 SetPetAction = <function> defined =[C]:-1
 SetLootItem = <function> defined =[C]:-1
 FadeOut = <function> defined =[C]:-1
 SetBuybackItem = <function> defined =[C]:-1
 SetMerchantItem = <function> defined =[C]:-1
 SetupTextureCoordinates = <function> defined @SharedXML/Backdrop.lua:214
 HasBackdropInfo = <function> defined @

**Comment by Road-block** [comment]
Should be fixed in https://github.com/Road-block/WaylaidTooltipHelper/commit/a79ada639ded3292be70798acef6cd59f0d78d0c thanks for the report.
